version: "3.9"
services:
  app:
    image: cloud-run-test
    build:
      context: ./Dockerfile
      args:
        - target=deploy-builder
    environment:
      TODO_ENV: prod
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - '8080:8080'