version: "3.9"
services:
  app:
    image: linebotsrv01
    build:
      args:
        - target=deploy-builder
    environment:
      ENV: prod
      PORT: 8080
      DB_HOST: linebotsrv02
      DB_PORT: 3306
      DB_USER: todo
      DB_PASSWORD: P@ssw0rd
      DB_NAME: linebot
    volumes:
      - .:/app
  linebotsrv02:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name:  tododb01
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: linebot
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: linebot
      MYSQL_TCP_PORT: 3306
    volumes:
      - tododb01-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - '3306:3306'
volumes:
  tododb01-data: